pestphp/docs

- coverage.md
- guides/command-line.md
Two updates:
1) The 'Next Section' link at the end of the **Coverage** page doesn't move to Command Line page. Instead, it links to the PHPUnit page. It should move to the Command Line page as per the table of contents.
2) In Command Line page, there was no link to the PHPUnit page as continuation. That has been added.
> Next section link in Coverage skips the Command line page

- guides/laravel.md
The old docs use `factory(User::class)->create()` helper. I think it should be updated to the latest laravel syntax and use `User::factory()->create()` instead.
> Use laravel 8 factory syntax

- skipping-tests.md
Replacing https://github.com/pestphp/website/pull/96/commits/31ff0d45c60d92111a7314e011f65b90fc66c253
> Add example for skip usage on higher order testing

- plugins/livewire.md
Hi! This is a simple typo fix on the livewire plugin doc. Thanks for the great test framework!
> Fix typo on livewire plugin doc

- guides/plugins.md
I caught a few small typos with some internal anchors on the Creating Plugins page. This PR resolves them.
> Fix internal link anchors on Creating Plugins page

- documentation.md
- plugins/creating-plugins.md
- plugins/watch.md
This applies the changes from https://github.com/pestphp/website/pull/52 which is now in an archived repository.
I've marked this PR as draft as the plugin isn't ready yet.
I've also marked the 89acfb3c7fd4ca3751ecf91fc528880a8ed51659 commit as co-authored by @caneco and @AlexMartinFR.
> docs: add page for the Watch plugin

- setup-and-teardown.md
- underlying-test-case.md
- add some documentation for reusable/shared setup & teardown hooks
See pestphp/pest#282
> reusable/shared setup & teardown documentation

- plugins/mock.md
Related to https://github.com/pestphp/pest-plugin-mock/pull/3, I think it should be noted that this plugin requires PHP 8 intentionally.
> chore: add note about PHP 8 requirement for Mock plugin

- assertions.md
- coverage.md
Phpunit docs page for 9.0 renders a 404, updated to 9.5
**Note:**  
The file `cli-options.md` links to `phpunit.readthedocs.io/en/latest/`,  however Pest `composer.json` contains `"phpunit/phpunit": ">= 9.3.7 <= 9.5.4"`. Can this generate any sort of confusion or would be best to link everything to `latest`?
Thanks
> Fixing broken links

- plugins/laravel.md
In Laravel Plugin, in the pest:install section we found an error where the Pest.php file is located
> chore[laravel.md]: typo in test/Pest.php

- helpers.md
- ide-plugins.md
I noticed the IDE Plugins Page is different from other pages in the documentation because it lacks the Next Section Button.
I also changed the Next Section URL in the Custom Helpers page to the IDE Plugins Page to improve the reading experience.
This is my first pull request. If there are any mistakes, please forgive me.
> Add Next Section URL in IDE Plugins Page to Exceptions & Errors Page

- expectations.md
Details about the exception are shown, but it's not included in the list of available expectations.
> Add toBeArray() to list of available expectations

- exceptions-and-errors.md
This documents the following PR:
- https://github.com/pestphp/pest/pull/339
> Adds documentation for skipping the exception type in `throws`

- higher-order-tests.md
This adds documentation for the following PR:
- https://github.com/pestphp/pest/pull/352
> Adds documentation for using datasets in higher order tests

- documentation.md
- plugins/snapshots.md
- plugins/time.md
This PR adds the docs for Time plugin: https://github.com/spatie/pest-plugin-test-time 
I did not find where the menu structure of https://pestphp.com/docs is being managed, so that one needs to be updated as well.
> Add Time plugin

- expectations.md
- adds the ":string" typehint to the `IsValidUrlConstraint()`-Constraint example (so it matches the extended `PHPUnit\Framework\Constraint\Constraint::toString()`
> update/Typehint returntype `IsValidUrlConstraint()`

- documentation.md
Me again,
didn't quite twig how the sidebar loaded the items and forgot to add the money plugin to the sidebar.
This fixes that.
> Adds money plugin to sidebar

- expectations.md
this PR will update docs to clarify the ability to use multiple needles in `toContain()` expectation
ref [#365](https://github.com/pestphp/pest/pull/365)
> Updates expect()->toContain() docs

- plugins/laravel.md
Apologies, missed this on the original PR.
If you add the TestSuite entry then your tests will fail if you run `./vendor/bin/pest` or `php artisan test`. Whilst it feels against the grain, this appears to be what's required to get Dusk tests running
> Remove phpunit.xml entry

- expectations.md
- Adds documentation for `toHaveLength()` expectation method.
- Changelog not updated as release is not tagged.
> Adds doc for toHaveLength

- cli-options.md
Currently the `->only()` link in **CLI Options** `--ci` is leading to a 404, this PR fixes that by adding the missing `/` in front of the relative URL like all other relative links have.
> Fix `->only()` link leading to 404.

- plugins/mock.md
Calling `->once` causes an exception when running tests. It should be called with parenthesis as `->once()`
> Fix typo in calling `->once` method

- cli-options.md
- groups.md
A simple PR to mention `exclude-group` in the [CLI Options](https://pestphp.com/docs/cli-options) and [Groups Of Tests](https://pestphp.com/docs/groups) pages.
> Update docs to include exclude-group

- plugins/mock.md
Attempting to use the second mock example, as described, results in two errors:
`call_user_func_array(): Argument #1 ($callback) must be a valid callback, class Mockery\Expectation does not have a method "isSet"`
This is because, as described, an `ExpectationInterface` object is returned, not a `MockInterface` object.
`Method isSet(<Any Arguments>) from Mockery_0_WeatherStation_Service_WeatherService should be called exactly
1 times but called 0 times.`
This is because of using `once()`.
I suggest the fix in this commit to correct both issues. I appreciate it's an arbitrary example, but I feel that this will help.
> Correct small issues in the mock documentation

- coverage.md
Currently these options are only covered on the "cli-options" page and not in the main coverage section.
> add reference to coverage-xml and coverage-html

- plugins/mock.md
We should be linking to the HTTPS versions of websites where possible.
> Use HTTPS for external URL

- expectations.md
The 'hello' => 'world' associative iterable [sequence expectation example](https://pestphp.com/docs/expectations#sequence) has the key 'hello' in the expectation instead of the value 'world'.
> Corrects error in sequence expectation example

- plugins/faker.md
`faker()` has been renamed to `fake()` in pest-plugin-faker.
> Updated faker.md to correct function name

- plugins/creating-plugins.md
Changelog, where the link was pointing, is not present anymore. Linking to the next menu item - Support Policy - instead.
If that's the expected behaviour then it...
Fixes #147
> Fix next section link in creating plugins page

- expectations.md
Use the `dd` method to dump**~~s~~** the current expectation value and end**~~s~~** the script:
> dd() description typos fixed

- expectations.md
This PR adds the following Expectations:
-  `toContainOnlyInstancesOf()` from https://github.com/pestphp/pest/pull/520
- `toBeFile()`, `toBeReadableFile()` and `toBeWritableFile()` from https://github.com/pestphp/pest/pull/162
Also changed the example in `ToBeEmpty()` to show where/how it works.
> Add missing Expectations

- filtering-tests.md
Hi, thanks for Pest and for the amazing docs :)
This PR is a simple fix for the `--exclude-group` section so it uses the correct command option.
> fix: use correct command option

- continuous-integration.md
This PR adds an example configuration to run tests written with Pest on GitLab CI/CD pipelines.
> Add example configuration for GitLab CI/CD Pipelines

- custom-helpers.md
This PR includes `tests/Helpers` directory information in the "Custom Helpers" section in response to the issue https://github.com/pestphp/pest/issues/734
> Add Helpers directory information

- plugins.md
This add the installation of `fswatch` to the installation process.
When running `--watch` for the first time and having the [error message](https://github.com/pestphp/pest-plugin-watch/blob/fce573f06a39ff2114dfc0fe5abd40b3c456401d/src/Plugin.php#L113-L120), I wondered if I did something wrong or if there was a bug. Only after `fswatch` installation and running it again, came the relief. 😌
The plugin seems to work well at first sight, so many thanks. It’s very useful!
> Add link to `fswatch` in Watch plugin

- upgrade-guide.md
Congrats on the v2 release! This caught me as I was upgrading to Pest v2.
This PR:
- Adds instructions for the Faker Plugin to the upgrade guide, advising users to find and replace `faker()` -> `fake()`
> Add Faker Plugin upgrade guide

- expectations.md
- higher-order-testing.md
This PR adds "Higher Order Expectations" and "Scoped Higher Order Expectations".
I have also improved the standards in Expectations page. 
- Remove blank lines between expect functions(). Some examples had it, others didn't.
- Use "ensures" everywhere instead of "confirms", "verifies", "guarantees", etc.
> Add Higher Order Expectations and Scoped Higher Order Expectations

- cli-api-reference.md
`--process-isolation` option isn't supported but it's listed in the docs which could be a bit confusing.
There is technically a handler for it in the code but it just returns an error to say its not supported.
Alternatively we could add a note in the docs to say explicitly its not supported?
See:
https://github.com/pestphp/pest/issues/618
> Update `cli-reference.md` to remove reference to `--process-isolation` option.

- custom-expectations.md
- custom-helpers.md
- exceptions.md
- expectations.md
- filtering-tests.md
- grouping-tests.md
- higher-order-testing.md
- mocking.md
- skipping-tests.md
- upgrade-guide.md
- writing-tests.md
This PR fixes the heading on `Higher Order Testing` and corrects inconsistencies when writing about functions and methods. 
We can find both usages: "use the method **foo()** to..." and "use the method **foo** to...".
For example:
```plain
It is important to remember that the it() function prefixes [...]
As an alternative to the test function, Pest provides the convenient it function that [...]
```
```plain
[...] you can use to test the behavior of your code, such as toBeTrue [...]
[...] you can replace the toBe() expectation to check [...]
```
In this PR, I've changed all the occurrences to the `foo()` style, which appears most often in the documentation. 
Adopting and following this visual consistency makes the documentation easier for beginners.
> Small general fixes

- plugins.md
- writing-tests.md
This PR adds an example for actingAs helper.
I have tried to improve the user experience with searching for this content by including the words `"acting as"`and namespaced functions in the text.
In addiction, I've referenced Laravel's test documentation link to allow users to read more Laravel content.
> Add actingAs example to Laravel plugin

- announcing-pest2.md
- why-pest.md
This PR adds the missing link to Spatie's Snapshot plugin and updates the figure on parallel test improvement.
> Snapshot plugin link and update improvement on parallel test

- video-resources.md
Pest from scratch has it's own domain, so I've updated the docs to use that instead 😎
> Update Pest From Scratch link

- expectations.md
This PR will add a new example for `toThrow()` including the new check implemented in https://github.com/pestphp/pest/pull/797
> Add toThrow(new Exception('message')) to docs

- installation.md
I've noticed that there is an error 404 link on the Installation Page pointing to [Migration Guide →](https://pestphp.com/docs/migration-from-phpunit). Instead, it should be pointing to [Migration Guide →](https://pestphp.com/docs/migrating-from-phpunit-guide)
> Link to "Migrating from PHPUnit guide" corrected

- installation.md
The migration guide link at the bottom of the page was leading to a 404.
> Update the "Migration Guide" link at the bottom of the page

- upgrade-guide.md
Just trying to debug an issue with Scoped Datasets and the URL on the upgrade guide references an invalid element ID for the Scoped Datasets URL.
Appears the working element ID requires `content-` prefixed to it, as seen on the live docs:
This PR is simply to apply that fix to the referenced URL.
> Fix broken link to Scoped Datasets

- configuring-tests.md
This commit adds documentation for the recently merged feature that allows the use of PHP glob patterns in the `->in()` method. This feature was introduced in the following pull request:
- [Pull Request #829](https://github.com/pestphp/pest/pull/829)
The new documentation explains how to use glob patterns in Pest's configuration file to specify multiple directories or files with a single pattern and provides examples for better understanding:
1. Applying a base test case class to all test files in a directory that match a specific pattern:
```php
// tests/Pest.php
uses(Tests\TestCase::class)->in('Feature/*Job*.php');
```
2. Using a glob pattern to match multiple directories in different modules while applying multiple test case classes and traits:
```php
// tests/Pest.php
uses( …
```
> Add documentation for glob patterns in ->in() method

- continuous-integration.md
Related to: https://github.com/pestphp/docs/issues/200
> Remove `--ansi` Option from BitBucket CI Example

- arch-testing.md
Related to: https://github.com/pestphp/pest/pull/947
> [2.x] Add `toHaveMethod`. New Arch Expectation

- arch-testing.md
Hey! I was just searching through the architecture docs looking for the `ignoring` modifier and noticed that the link to snap to that section looked a bit broken.
This seems to solve the issue, but apologies in advance if I've not done it right though 🙂
> Fixed broken link

- arch-testing.md
Currently the heading link is `#enums` as there is a gap between these.
> fix: resolve heading link for enum modifier

- expectations.md
Adds documentation for the recently added `toHaveConstructor()` and `toHaveDestructor()` expectations (in https://github.com/pestphp/pest/pull/962)
> docs for toHaveConstructor and toHaveDestructor expectations

- test-coverage.md
> docs: update deprecated `<coverage>` config usage

- expectations.md
Hi, 
I found this small error and corrected it.
The key name was used instead of the value.
> Using the good value instead of the key name

- stress-testing.md
Thos PR adds documentation for the stressless option to switch between GET and POST http methods.
Depends on merging of https://github.com/pestphp/pest-plugin-stressless/pull/8
> feat(methods): Documented stressless new option to specify the http method

- type-coverage.md
Added "Different formats" documentation, attempting to keep it as similar as the `code-coverage.md` file.
> Plugin `pest-plugin-type-coverage`: Add new `--type-coverage-json` argument

- cli-api-reference.md
There was some MD markup which didn't render when parsed, since it was interpreted as an HTML tag.
> docs: fix wrong format

- arch-testing.md
Docs for https://github.com/pestphp/pest/pull/1006
> docs for `toBeStringBackedEnum()` and `toBeIntBackedEnum()` Arch Expectations

- arch-testing.md
This PR will fix the usage of `test` instead of `arch` in the architecture testing documentation
> Fix use of arch function instead of test

- writing-tests.md
I saw _rominronin_ reported this error on Discord and you asked a PR to fix it in February, but he didn't make it, so I'm here :)
On [writing tests](https://pestphp.com/docs/writing-tests)  page, the float example is wrong, so I fixed it :
```diff
describe('sum', function () {
it('may sum integers', function () {
$result = sum(1, 2);
expect($result)->toBe(3);
});
it('may sum floats', function () {
$result = sum(1.5, 2.5);
-      expect($result)->toBe(4);
+      expect($result)->toBe(4.0);
});
});
```
> Fix `float` expectation example

- test-dependencies.md
This PR removes an unnecessary assertion in the code example.
> Removes unnecessary assertion

- continuous-integration.md
It was saying GitLab instead of Bitbucket there 🗿
> Adjust 'Example with Bitbucket Pipelines' on Continuous Integration page

- pest-spicy-summer-release.md
I think those two are correct, old copy was a mixture of the two:
- to automatically convert
- for automatically convert
> Typo in spicy summer release docs

- continuous-integration.md
Using `--ci` can save you if you accidently add a `->only()`  to one of your tests, which would prevent the whole testsuite from running. [See `Only` plugin](https://github.com/pestphp/pest/blob/853f6efce6bc86636f48a0e921a44ccee9a66cf3/src/Plugins/Only.php#L43-L45)
I guess the idea behind `--ci` was also well. To run it during continuous integration :)
> Add `--ci` parameter to examples

- arch-testing.md
adds missing () on the arch testing page
> fix: add missing () to `toHaveLineCountLessThan` in list

- expectations.md
Hello everybody,
This PR proposes adding a simple example for a expect testing `toBeDigits()`.
The idea is motivated by my misunderstanding for the test expectation.
> docs: add two new examples to undestand `->toBeDigits`

- datasets.md
Second attempt at #279. 
I wasn't sure if you meant to not include an example, or to use a markdown code block to give the example instead.
Let me know if you want me to exclude the example all together.
Thanks!
> Add explanation of dataset name interpolation - With Markdown instead of webp

- arch-testing.md
I have updated the custom presets section in the arch tests docs to reflect the correct syntax and description.
Note: `dump()` changed to `var_dump` in the example closure with the namespaces, because the closure is invoked/called in the autoloader and doesn't have application scope, so it causing an error when using dump within the closure, then running the custom preset in the example.
This error:
```
Call to undefined method Illuminate\Container\Container::basePath()
phar:///Applications/Herd.app/Contents/Resources/valet/dump.phar/src/HerdDumper.php:33
```
However, if you'd prefer to leave it as dump, just for the sake of the example, I can change it back.
> Fix: Update custom presets to reflect correct syntax and description.

- grouping-tests.md
Hey,
This PR fixes a small typo in the `grouping-test.md` file.
> Fix typo in grouping-tests

- mutation-testing.md
> Add missing --mutate option to the example provided for the --everything option

- pest3-now-available.md
The link for team management was incorrect and just linked to the section of the same page.
> Fix incorrect team management link

- cli-api-reference.md
Looks like this flag was missing? Unless I'm missing something.
> chore(docs): add missing `--ci` flag to CLI API ref
