pestphp/docs

plugins/faker.md
This follows the release of v0.3.1 of the [Faker plugin](https://github.com/pestphp/pest-plugin-faker). 👍🏻
=> docs(plugins.faker): update links to FakerPHP

expectations.md
changed duplicate toBeInstanceOf -> toBeBool
=> Duplicate tobeInstanceOf

coverage.md
Relies on https://github.com/pestphp/pestphp.com/pull/7 being merged for the `diff` highlighting. 👍🏻
=> docs: add details on coverage filters

expectations.md
Documentation for [this feature](https://github.com/pestphp/pest-plugin-expectations/pull/2).
=> docs: adds `toBeJson` to expectations.md

cli-options.md, community.md, contribute.md, coverage.md, expectations.md, groups.md, helpers.md, installation.md, setup-and-teardown.md, skipping-tests.md, upgrade-guide.md, writing-tests.md
Fixed most remaining grammatical errors or typos on the docs.
=> Minor corrections

plugins/watch.md
- Matches the top navigation structure found in other plugins page
- Divided into sections to provide an easier access on possible questions
=> Navigation structure and sectionalization

cli-options.md
Related to https://github.com/pestphp/pest/pull/283
=> document `--test-directory` option

coverage.md
Adding additional information on what the output of missing coverage looks like.
=> Extending coverage explanation

datasets.md
This will add docs to explain the new features added with this core repository PR: pestphp/pest#303
=> adds matrix datasets docs

expectations.md
This PR adds documentation for Higher Order Expectations as introduced in [this PR](https://github.com/pestphp/pest-plugin-expectations/pull/12).
=> Adds documentation for higher order expectations

expectations.md
Added `json()` to expectations page.
=> docs: Add json() to expectation

expectations.md
Sorry, it was missing in the method list.
=> add json() to link menu

plugins/laravel.md
related to: pestphp/pest-plugin-laravel#13
=> add toBeCollection docs for Laravel Plugin

expectations.md
This PR adds documentation for the following PRs:
- https://github.com/pestphp/pest/pull/324
- https://github.com/pestphp/pest/pull/323
- https://github.com/pestphp/pest/pull/322
=> Adds documentation for new features

higher-order-tests.md
This adds documentation for:
-  https://github.com/pestphp/pest/pull/331
=> Adds documentation for `tap` and closure to `expect`

skipping-tests.md
This adds documentation for the following PR:
- https://github.com/pestphp/pest/pull/338
=> Adds documentation for the test case aware skip method

higher-order-tests.md
This adds documentation for the following PR:
- https://github.com/pestphp/pest/pull/341
=> Adds documentation for using higher order expectations in higher order tests

plugins/time.md
Made a mistake in the heading, sorry about that 🙂
=> Fix heading

setup-and-teardown.md
The `uses()->in()` method "returns" `void` so it has to be the last one in the method chain.
Took me some minutes to fix as I've only copied from the docs. 🙈
=> fix reusable setup example

plugins/mock.md, plugins/money.md
Hi guys,
This PR adds documentation for the Pest Money plugin: https://github.com/lukeraymonddowning/pest-plugin-money
Kind Regards,
Luke
=> Adds documentation for the money plugin

datasets.md
This adds documentation for the following PR:
- https://github.com/pestphp/pest/pull/364
Kind Regards,
Luke
=> Adds documentation for bound datasets

expectations.md
Pest PR: https://github.com/pestphp/pest/pull/391
=> Add doc for toHaveProperties

writing-tests.md
Not much but honest work. It's more readable with three dots.
=> Changed ..Test.php into ...Test.php

expectations.md
pestphp/pest#407
pestphp/pest#406
pestphp/pest@b43a59868d5b790a28cbb29c6110c9f068b0b812
=> Adds documentation for `match()`, `when()` and `unless()`

exceptions-and-errors.md
=> Adds Documentation for `throwsIf()`

cli-options.md, skipping-tests.md
this PR add docs for https://github.com/pestphp/pest/pull/405
=> update cli docs to add --ci option

cli-options.md, groups.md
- Fix broken link to PHPUnit doc
- Added examples on --group and --exclude-group
- Added '--order-by' option
- Fix broken link on `Groups`
=> Update Cli Options: adds --order-by

plugins/creating-plugins.md
It's just an example, but still...
=> Update `fzaninotto` to `fakerphp` in faker example

documentation.md, groups.md, test-dependency.md
Documentation page for `->depends()` method.
Original PR: https://github.com/pestphp/pest/pull/103
=> [1.x] Add Test Dependency page

expectations.md
This relates to https://github.com/pestphp/pest/pull/652, I couldn't find a `next` branch here, so assuming it's this one that you meant?
=> docs: add `toHaveMethod` and `toHaveMethods`

datasets.md
This PR makes the example compatible with the function `sum`.
=> Improve closure example

installation.md
I think this is an oversight, so a simple deletion
=> Correct wording issue in Installation docs

community-guide.md
This PR updates the Discord link to a valid one.
=> Update Discord link

continuous-integration.md
I've been asked a bunch of about using Pest with Chipper, and thought this would be useful!
=> Using Pest with Chipper CI

video-resources.md
As previously discussed, this PR improves the video page, adding new resources.
`❗` Important changes: I have switched from `https` to `http` in http://pestfromscratch.com/ because of an issue accessing the domain with https.
=> Improve video resource page

expectations.md
Refers: https://github.com/pestphp/pest/pull/911
=> Introducing `toBeDigits` Expectation

expectations.md
Refers: https://github.com/pestphp/pest/pull/924
=> `toHaveSameSize` expectation usage

custom-expectations.md
Related to: https://github.com/pestphp/pest/issues/944
=> [2.x] Explanation About Custom Expectations Using `and` 

arch-testing.md
Related to: https://github.com/pestphp/pest/pull/934
=> [2.x] Add `toHaveAttribute` New Arch Expectation

expectations.md
Refers: https://github.com/pestphp/pest/pull/948
=> [2.x] Add `toBeUuid` expectation usage

arch-testing.md
https://github.com/pestphp/docs/pull/230 but slightly reworded and put in the correct place
=> docs for toHaveConstructor and toHaveDestructor expectations

expectations.md
Docs for https://github.com/pestphp/pest/pull/968
=> add docs for `toBeBetween` expectation

expectations.md
Docs for https://github.com/pestphp/pest/pull/977
=> add docs for `toBeUrl()` expectation

exceptions.md
It wasn't written, so wrote it.
=> Add `throwsNoExceptions()` to exceptions

skipping-tests.md
This PR documents the newly added onlyOnWindows, onlyOnMac and onlyOnLinux methods
=> feat: onlyOn* methods

type-coverage.md
I was reviewing the docs, and noticed this little typo.
=> Typo on Pest Type Coverage Page

custom-helpers.md
Hey Pest Team,
The PR updates the reference from "Features" to the more commonly used "Feature" based on the other docs. Also, I've updated the visibility on the method to match the description above the example.
=> Update custom-helpers.md with more consistent use of "Feature"

migrating-from-phpunit-guide.md
Hello @nunomaduro, I hope you are good and your dear colleagues too. :+1: 
Was looking to implement the above feature when I saw it implemented in the code here:
https://github.com/pestphp/pest-plugin-drift/blob/cd506d2b931eb1443b878229b472c59d6f2d8ee8/src/Plugin.php#L48-L54
Let me know if you would like me to do some changes in wording.
Thank you all guys for amazing plugin and work. Very much appreciated. :1st_place_medal:
=> Add documentation to run pest drift for certain folder only

grouping-tests.md
Fixing the example on line 40.
=> fix grouping-tests.md example
